export class DiagnosticsData {
  // formData : 
  constructor(
    public entityName: string,
    public tradingName: string,
    public regOffice: string,
    public placebusiness: string,
    public abnNumber: number,
    public address1: string,
    public address2: string,
    public city: string,
    public zip: string,
    public entity: string,
    public noofemployee: number,
    //2
    public f2name: string,
    public f2email: string,
    public f2gender: boolean,
    public f2pan: string,
    public f2aadhar: string,
    public f2dl: string,
    public f2placebusiness: string,
    public f2empnumber: string,
    public f2address1: string,
    public f2address2: string,
    public f2city: string,
    public f2zip: string,
    // 3
    public f3entityName: string,
    public f3tradingName: string,
    public f3regOffice: string,
    public f3placebusiness: string,
    public f3abnNumber: number,
    public f3address1: string,
    public f3address2: string,
    public f3city: string,
    public f3zip: string,
    public f3entity: string,
    public f3noofemployee: number,
    //4
    public f4name: string,
    public f4email: string,
    public f4gender: boolean,
    public f4pan: string,
    public f4aadhar: string,
    public f4dl: string,
    public f4placebusiness: string,
    public f4empnumber: string,
    public f4address1: string,
    public f4address2: string,
    public f4city: string,
    public f4zip: string,
    //5
    public f5entityName: string,
    public f5tradingName: string,
    public f5regOffice: string,
    public f5placebusiness: string,
    public f5abnNumber: number,
    public f5address1: string,
    public f5address2: string,
    public f5city: string,
    public f5zip: string,
    public f5entity: string,
    public f5noofemployee: number,
    //6
    public f6name: string,
    public f6email: string,
    public f6gender: boolean,
    public f6pan: string,
    public f6aadhar: string,
    public f6dl: string,
    public f6placebusiness: string,
    public f6empnumber: string,
    public f6address1: string,
    public f6address2: string,
    public f6city: string,
    public f6zip: string,
    // 7
    public f7entityName: string,
    public f7tradingName: string,
    public f7regOffice: string,
    public f7placebusiness: string,
    public f7abnNumber: number,
    public f7address1: string,
    public f7address2: string,
    public f7city: string,
    public f7zip: string,
    public f7entity: string,
    public f7noofemployee: number,
    //8
    public f8name: string,
    public f8email: string,
    public f8gender: boolean,
    public f8pan: string,
    public f8aadhar: string,
    public f8dl: string,
    public f8placebusiness: string,
    public f8empnumber: string,
    public f8address1: string,
    public f8address2: string,
    public f8city: string,
    public f8zip: string,
// 9
    public f9entityName: string,
    public f9tradingName: string,
    public f9regOffice: string,
    public f9placebusiness: string,
    public f9abnNumber: number,
    public f9address1: string,
    public f9address2: string,
    public f9city: string,
    public f9zip: string,
    public f9entity: string,
    public f9noofemployee: number,
    //2
    public f10name: string,
    public f10email: string,
    public f10gender: boolean,
    public f10pan: string,
    public f10aadhar: string,
    public f10dl: string,
    public f10placebusiness: string,
    public f10empnumber: string,
    public f10address1: string,
    public f10address2: string,
    public f10city: string,
    public f10zip: string
  ) {}
}